services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: tinyinsta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tinyinsta"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

  bench:
    build:
      context: ./bench
    depends_on:
      db:
        condition: service_healthy
    working_dir: /work
    volumes:
      - ./:/work
    environment:
      PGPASSWORD: postgres
    command: ["sleep", "infinity"]

volumes:
  pgdata:
