services:
  coordinator:
    image: citusdata/citus:12.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    ports:
      - "5432:5432"
    networks:
      - citusnet
    depends_on:
      - worker1
      - worker2

  worker1:
    image: citusdata/citus:12.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    networks:
      - citusnet

SELECT * FROM master_add_node('worker1', 5432);  worker2:
    image: citusdata/citus:12.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    networks:
      - citusnet

networks:
  citusnet:
